# fly.toml app configuration file generated for notes-app-testing on 2023-09-28T16:43:35-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "notes-app-testing"
primary_region = "ewr"

[build]

[env]
  PORT = "3000"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
