GET http://localhost:3001/api/users

###
POST http://localhost:3001/api/users HTTP/1.1
Content-Type: application/json

{
  "username": "user",
  "name": "Test user",
  "password": "secret"
}

###
POST http://localhost:3001/api/users HTTP/1.1
Content-Type: application/json

{
  "username": "tester",
  "name": "Test user dogcoin",
  "password": "secret"
}
